---
org: [ORGANISATION_NAME]
app: [APP_NAME]
service: [SERVICE_NAME]

frameworkVersion: '2'
useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  deploymentBucket: [DEPLOYMENT_BUCKET]

  role: [ROLE_ARN]
  environment:
    STAGE: ${self:provider.stage}

custom:
  configFile: ${file(config.json)}
  bucket: ${self:custom.configFile.${self:provider.stage}.OUTPUT_BUCKET}
  pythonRequirements:
    dockerizePip: non-linux

functions:
  main:
    handler: src/handler.main
    timeout: 20
    memorySize: 1024
    reservedConcurrency: 1
    events:
      - s3:
         bucket: ${self:custom.bucket}
         event: s3:ObjectCreated:*
         rules:
          - prefix: ${self:custom.configFile.${self:provider.stage}.PROCESS_FOLDER}
          - suffix: .csv
         existing: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

package:
  patterns:
    - '!data/**'
    - '!__pycache__/**'
    - '!.serverless/**'
    - '!.private/**'
    - '!.pytest_cache/**'
    - '!**.ipynb**'
